name: whispers_of_the_loom
description: "A digital archive for collectors of domestic textile antiquities and pioneer-era spinning crafts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#F8F5F0"
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F8F5F0"
  image: "assets/images/logo.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/logo.png"
    color: "#F8F5F0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
